// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkvqyjfeaglirydxbuof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdnF5amZlYWdsaXJ5ZHhidW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTczNzMsImV4cCI6MjA3NDczMzM3M30.fmEA-2MclSWP6QNE3xhqOC3cktT5_I3OLb0t0040rAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});